<?xml version="1.0"?>
<package format="3">
  <name>sensor_drivers</name>
  <version>0.1.0</version>
  <description>Sensor integration wrappers for USB webcam and robot sensor bring-up.</description>
  <maintainer email="nithish@example.com">Nithish</maintainer>
  <license>MIT</license>

  <buildtool_depend>ament_cmake</buildtool_depend>

  <depend>amr_interfaces</depend>
  <depend>rclcpp</depend>
  <depend>sensor_msgs</depend>
  <depend>std_msgs</depend>

  <export>
    <build_type>ament_cmake</build_type>
  </export>
</package>

