<?xml version="1.0"?>
<package format="3">
  <name>localization_slam_mapping</name>
  <version>0.1.0</version>
  <description>Online 2D mapping profile for SLAM Toolbox.</description>
  <maintainer email="nithish@example.com">Nithish</maintainer>
  <license>MIT</license>

  <buildtool_depend>ament_cmake</buildtool_depend>
  <exec_depend>ament_index_python</exec_depend>
  <exec_depend>launch</exec_depend>
  <exec_depend>launch_ros</exec_depend>
  <exec_depend>slam_toolbox</exec_depend>

  <export>
    <build_type>ament_cmake</build_type>
  </export>
</package>
