FROM osrf/ros:humble-desktop

SHELL ["/bin/bash", "-c"]

RUN apt-get update && apt-get install -y --no-install-recommends \
    build-essential \
    cmake \
    git \
    python3-colcon-common-extensions \
    python3-vcstool \
  && rm -rf /var/lib/apt/lists/*

WORKDIR /workspaces/jetauto_orin_amr
