<?xml version="1.0"?>
<package format="3">
  <name>cuda_common</name>
  <version>0.1.0</version>
  <description>Reusable CUDA resource, error handling, stream, and timing utilities.</description>
  <maintainer email="nithish@example.com">Nithish</maintainer>
  <license>MIT</license>

  <buildtool_depend>ament_cmake</buildtool_depend>

  <export>
    <build_type>ament_cmake</build_type>
  </export>
</package>

